### PR TITLE
EricM5 - Add Github info to /api/SystemInfo endpoint and display on Developer Page

### PR DESCRIPTION
**Pull request by EricM5**
Broken off from #8 .

Changed pom.xml, Add Github info to /api/SystemInfo endpoint and display on Developer Page

Dokku: https://proj-courses-ericm5-dev.dokku-12.cs.ucsb.edu/

(Merge #42 before).

When run locally:
image

### CODE REVIEW

**Comment by anisavic** [comment]
Hey Eric, I'm going to check out your code more deeply, but one easy way for your checks to pass is by making sure your files are formatted. To do that, just cd frontend, then npm run format.

**Review by Bennyyyyy — DISMISSED** [review]
LGTM

**Review by apzhou0 — APPROVED** [review]
LGTM

**Review by anisavic — DISMISSED** [review]
LGTM

**Review by GlassBricks — DISMISSED** [review]
LGTM; remember to resolve merge conflicts

**Review by anisavic — APPROVED** [review]
LGTM

**Pull request merged**
