### PR TITLE
azhou - CourseDetailsPage Invalid Quarter/Code Error Handling

### LINKED ISSUE #53: Fix Invalid Quarter/Enroll Code Error Screen
Invalid quarter/enroll code should show a message such as: "Quarter is not formatted properly" or "Enroll code 12345 does not exist for W22" rather than white screen of death for "/coursedetails/{quarter}/{enrollCode}"

Fixes error in #37

### PR DESCRIPTION
**Pull request by apzhou0**
In this PR, we add an error page for invalid quarter/enroll code params to fix the issue brought up in #37. 

Dokku Link:  https://proj-courses-apzhou0-dev.dokku-12.cs.ucsb.edu/

To test, add "coursedetails/{invalidquarter}/{invalidcode}" to the end of the link above. For example: https://proj-courses-apzhou0-dev.dokku-12.cs.ucsb.edu/coursedetails/20221/2029a. This should bring you to an error page and not the white screen of death, as shown below. 

image

CourseDetailsPage Storybook Link: https://ucsb-cs156-f23.github.io/proj-courses-f23-7pm-4/prs/66/storybook/?path=/docs/pages-coursedetails-coursedetailspage--default

Closes #53

### CODE REVIEW

**Comment by Bennyyyyy** [comment]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!  Nicely done

**Comment by anisavic** [comment]
LGTM

**Review by Bennyyyyy — APPROVED** [review]
LGTM

**Pull request merged**
