### PR TITLE
Sasha - EPIC for better job logs, Part 1

### LINKED ISSUE #62: Epic: Better Job Logs, Part 1
`### Acceptance Criteria

- [ ] When log output is less than ten lines, the entire output is displayed on the main jobs table

### PR DESCRIPTION
**Pull request by anisavic**
In this PR, I have modified the Job Table to show only the first 10 lines when a job log is longer than 10 lines. Otherwise, when the log output is less than 10 lines, the entire output is displayed. This is part 1 for the EPIC issue.
image

Closes: #62

### CODE REVIEW

**Review by audoreven — APPROVED** [review]
LGTM

**Review by Bennyyyyy — APPROVED** [review]
LGTM

**Review by GlassBricks — APPROVED** [review]
LGTM; remember to resolve merge conflicts

**Review by pconrad — CHANGES_REQUESTED** [review]
Ok, so I'm not sure where this came from, and I like the idea, but there's an issue here.  There are times when you NEED to see the entire log output.   

So I don't think we can merge this unless it comes with some way to see the entire log output, such as, turning the <...> into a button or link that when pressed reveals the rest of the hidden output.

It's still very cool as a draft PR that would be a first step towards that.   If you choose not to move forward with implementing that part, I totally understand.  But I don't think this is mergeable in its current form, as it would take away an important tool for debugging problems with async jobs.

**Pull request closed without merging**
